# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: he_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'he_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10he_service.proto\x12\nhe_service\"\x0f\n\rKeyGenRequest\"F\n\x0eKeyGenResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\npublic_key\x18\x03 \x01(\x0c\"&\n\x0e\x45ncryptRequest\x12\x14\n\x0cplain_values\x18\x01 \x03(\x01\"%\n\x0f\x45ncryptResponse\x12\x12\n\nciphertext\x18\x01 \x01(\x0c\"$\n\x0e\x44\x65\x63ryptRequest\x12\x12\n\nciphertext\x18\x01 \x01(\x0c\"\'\n\x0f\x44\x65\x63ryptResponse\x12\x14\n\x0cplain_values\x18\x01 \x03(\x01\"L\n\nAddRequest\x12\x13\n\x0b\x63iphertext1\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63iphertext2\x18\x02 \x01(\x0c\x12\x14\n\x0cplain_values\x18\x03 \x03(\x01\"(\n\x0b\x41\x64\x64Response\x12\x19\n\x11result_ciphertext\x18\x01 \x01(\x0c\"Q\n\x0fMultiplyRequest\x12\x13\n\x0b\x63iphertext1\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63iphertext2\x18\x02 \x01(\x0c\x12\x14\n\x0cplain_values\x18\x03 \x03(\x01\"-\n\x10MultiplyResponse\x12\x19\n\x11result_ciphertext\x18\x01 \x01(\x0c\"\x89\x01\n\x0fGradientRequest\x12\x19\n\x11\x65ncrypted_weights\x18\x01 \x01(\x0c\x12\x0f\n\x07x_batch\x18\x02 \x03(\x01\x12\x0f\n\x07y_batch\x18\x03 \x03(\x01\x12\x11\n\tn_samples\x18\x04 \x01(\x05\x12\x12\n\nn_features\x18\x05 \x01(\x05\x12\x12\n\nlambda_reg\x18\x06 \x01(\x01\".\n\x10GradientResponse\x12\x1a\n\x12\x65ncrypted_gradient\x18\x01 \x01(\x0c\x32\xa7\x03\n\tHEService\x12\x45\n\x0cGenerateKeys\x12\x19.he_service.KeyGenRequest\x1a\x1a.he_service.KeyGenResponse\x12\x42\n\x07\x45ncrypt\x12\x1a.he_service.EncryptRequest\x1a\x1b.he_service.EncryptResponse\x12\x42\n\x07\x44\x65\x63rypt\x12\x1a.he_service.DecryptRequest\x1a\x1b.he_service.DecryptResponse\x12\x36\n\x03\x41\x64\x64\x12\x16.he_service.AddRequest\x1a\x17.he_service.AddResponse\x12\x45\n\x08Multiply\x12\x1b.he_service.MultiplyRequest\x1a\x1c.he_service.MultiplyResponse\x12L\n\x0f\x43omputeGradient\x12\x1b.he_service.GradientRequest\x1a\x1c.he_service.GradientResponseB\x0eZ\x0c./he_serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'he_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014./he_service'
  _globals['_KEYGENREQUEST']._serialized_start=32
  _globals['_KEYGENREQUEST']._serialized_end=47
  _globals['_KEYGENRESPONSE']._serialized_start=49
  _globals['_KEYGENRESPONSE']._serialized_end=119
  _globals['_ENCRYPTREQUEST']._serialized_start=121
  _globals['_ENCRYPTREQUEST']._serialized_end=159
  _globals['_ENCRYPTRESPONSE']._serialized_start=161
  _globals['_ENCRYPTRESPONSE']._serialized_end=198
  _globals['_DECRYPTREQUEST']._serialized_start=200
  _globals['_DECRYPTREQUEST']._serialized_end=236
  _globals['_DECRYPTRESPONSE']._serialized_start=238
  _globals['_DECRYPTRESPONSE']._serialized_end=277
  _globals['_ADDREQUEST']._serialized_start=279
  _globals['_ADDREQUEST']._serialized_end=355
  _globals['_ADDRESPONSE']._serialized_start=357
  _globals['_ADDRESPONSE']._serialized_end=397
  _globals['_MULTIPLYREQUEST']._serialized_start=399
  _globals['_MULTIPLYREQUEST']._serialized_end=480
  _globals['_MULTIPLYRESPONSE']._serialized_start=482
  _globals['_MULTIPLYRESPONSE']._serialized_end=527
  _globals['_GRADIENTREQUEST']._serialized_start=530
  _globals['_GRADIENTREQUEST']._serialized_end=667
  _globals['_GRADIENTRESPONSE']._serialized_start=669
  _globals['_GRADIENTRESPONSE']._serialized_end=715
  _globals['_HESERVICE']._serialized_start=718
  _globals['_HESERVICE']._serialized_end=1141
# @@protoc_insertion_point(module_scope)
