# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import he_service_pb2 as proto_dot_he__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/he_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HEServiceStub(object):
    """----------------------------------------
    準同型暗号(CKKS)演算を提供するgRPCサービス
    ----------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateKeys = channel.unary_unary(
                '/he_service.HEService/GenerateKeys',
                request_serializer=proto_dot_he__service__pb2.KeyGenRequest.SerializeToString,
                response_deserializer=proto_dot_he__service__pb2.KeyGenResponse.FromString,
                _registered_method=True)
        self.Encrypt = channel.unary_unary(
                '/he_service.HEService/Encrypt',
                request_serializer=proto_dot_he__service__pb2.EncryptRequest.SerializeToString,
                response_deserializer=proto_dot_he__service__pb2.EncryptResponse.FromString,
                _registered_method=True)
        self.Decrypt = channel.unary_unary(
                '/he_service.HEService/Decrypt',
                request_serializer=proto_dot_he__service__pb2.DecryptRequest.SerializeToString,
                response_deserializer=proto_dot_he__service__pb2.DecryptResponse.FromString,
                _registered_method=True)
        self.Add = channel.unary_unary(
                '/he_service.HEService/Add',
                request_serializer=proto_dot_he__service__pb2.AddRequest.SerializeToString,
                response_deserializer=proto_dot_he__service__pb2.AddResponse.FromString,
                _registered_method=True)
        self.Multiply = channel.unary_unary(
                '/he_service.HEService/Multiply',
                request_serializer=proto_dot_he__service__pb2.MultiplyRequest.SerializeToString,
                response_deserializer=proto_dot_he__service__pb2.MultiplyResponse.FromString,
                _registered_method=True)


class HEServiceServicer(object):
    """----------------------------------------
    準同型暗号(CKKS)演算を提供するgRPCサービス
    ----------------------------------------
    """

    def GenerateKeys(self, request, context):
        """1. 鍵生成とコンテキストの初期化 (keygen.go / context.go 関連)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Encrypt(self, request, context):
        """2. 暗号化と復号 (encrypt_decrypt.go 関連)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decrypt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Add(self, request, context):
        """3. 暗号演算 (evaluator.go 関連)
        暗号文同士、または暗号文と平文の加算
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiply(self, request, context):
        """暗号文同士、または暗号文と平文の乗算
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HEServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateKeys,
                    request_deserializer=proto_dot_he__service__pb2.KeyGenRequest.FromString,
                    response_serializer=proto_dot_he__service__pb2.KeyGenResponse.SerializeToString,
            ),
            'Encrypt': grpc.unary_unary_rpc_method_handler(
                    servicer.Encrypt,
                    request_deserializer=proto_dot_he__service__pb2.EncryptRequest.FromString,
                    response_serializer=proto_dot_he__service__pb2.EncryptResponse.SerializeToString,
            ),
            'Decrypt': grpc.unary_unary_rpc_method_handler(
                    servicer.Decrypt,
                    request_deserializer=proto_dot_he__service__pb2.DecryptRequest.FromString,
                    response_serializer=proto_dot_he__service__pb2.DecryptResponse.SerializeToString,
            ),
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=proto_dot_he__service__pb2.AddRequest.FromString,
                    response_serializer=proto_dot_he__service__pb2.AddResponse.SerializeToString,
            ),
            'Multiply': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiply,
                    request_deserializer=proto_dot_he__service__pb2.MultiplyRequest.FromString,
                    response_serializer=proto_dot_he__service__pb2.MultiplyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'he_service.HEService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('he_service.HEService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HEService(object):
    """----------------------------------------
    準同型暗号(CKKS)演算を提供するgRPCサービス
    ----------------------------------------
    """

    @staticmethod
    def GenerateKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/he_service.HEService/GenerateKeys',
            proto_dot_he__service__pb2.KeyGenRequest.SerializeToString,
            proto_dot_he__service__pb2.KeyGenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Encrypt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/he_service.HEService/Encrypt',
            proto_dot_he__service__pb2.EncryptRequest.SerializeToString,
            proto_dot_he__service__pb2.EncryptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Decrypt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/he_service.HEService/Decrypt',
            proto_dot_he__service__pb2.DecryptRequest.SerializeToString,
            proto_dot_he__service__pb2.DecryptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/he_service.HEService/Add',
            proto_dot_he__service__pb2.AddRequest.SerializeToString,
            proto_dot_he__service__pb2.AddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Multiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/he_service.HEService/Multiply',
            proto_dot_he__service__pb2.MultiplyRequest.SerializeToString,
            proto_dot_he__service__pb2.MultiplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
