// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package he_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HEServiceClient is the client API for HEService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HEServiceClient interface {
	// 1. 鍵生成とコンテキストの初期化 (keygen.go / context.go 関連)
	GenerateKeys(ctx context.Context, in *KeyGenRequest, opts ...grpc.CallOption) (*KeyGenResponse, error)
	// 2. 暗号化と復号 (encrypt_decrypt.go 関連)
	Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error)
	Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error)
	// 3. 暗号演算 (evaluator.go 関連)
	// 暗号文同士、または暗号文と平文の加算
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	// 暗号文同士、または暗号文と平文の乗算
	Multiply(ctx context.Context, in *MultiplyRequest, opts ...grpc.CallOption) (*MultiplyResponse, error)
}

type hEServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHEServiceClient(cc grpc.ClientConnInterface) HEServiceClient {
	return &hEServiceClient{cc}
}

func (c *hEServiceClient) GenerateKeys(ctx context.Context, in *KeyGenRequest, opts ...grpc.CallOption) (*KeyGenResponse, error) {
	out := new(KeyGenResponse)
	err := c.cc.Invoke(ctx, "/he_service.HEService/GenerateKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hEServiceClient) Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error) {
	out := new(EncryptResponse)
	err := c.cc.Invoke(ctx, "/he_service.HEService/Encrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hEServiceClient) Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error) {
	out := new(DecryptResponse)
	err := c.cc.Invoke(ctx, "/he_service.HEService/Decrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hEServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/he_service.HEService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hEServiceClient) Multiply(ctx context.Context, in *MultiplyRequest, opts ...grpc.CallOption) (*MultiplyResponse, error) {
	out := new(MultiplyResponse)
	err := c.cc.Invoke(ctx, "/he_service.HEService/Multiply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HEServiceServer is the server API for HEService service.
// All implementations must embed UnimplementedHEServiceServer
// for forward compatibility
type HEServiceServer interface {
	// 1. 鍵生成とコンテキストの初期化 (keygen.go / context.go 関連)
	GenerateKeys(context.Context, *KeyGenRequest) (*KeyGenResponse, error)
	// 2. 暗号化と復号 (encrypt_decrypt.go 関連)
	Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error)
	Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error)
	// 3. 暗号演算 (evaluator.go 関連)
	// 暗号文同士、または暗号文と平文の加算
	Add(context.Context, *AddRequest) (*AddResponse, error)
	// 暗号文同士、または暗号文と平文の乗算
	Multiply(context.Context, *MultiplyRequest) (*MultiplyResponse, error)
	mustEmbedUnimplementedHEServiceServer()
}

// UnimplementedHEServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHEServiceServer struct {
}

func (UnimplementedHEServiceServer) GenerateKeys(context.Context, *KeyGenRequest) (*KeyGenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateKeys not implemented")
}
func (UnimplementedHEServiceServer) Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Encrypt not implemented")
}
func (UnimplementedHEServiceServer) Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decrypt not implemented")
}
func (UnimplementedHEServiceServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedHEServiceServer) Multiply(context.Context, *MultiplyRequest) (*MultiplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Multiply not implemented")
}
func (UnimplementedHEServiceServer) mustEmbedUnimplementedHEServiceServer() {}

// UnsafeHEServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HEServiceServer will
// result in compilation errors.
type UnsafeHEServiceServer interface {
	mustEmbedUnimplementedHEServiceServer()
}

func RegisterHEServiceServer(s grpc.ServiceRegistrar, srv HEServiceServer) {
	s.RegisterService(&HEService_ServiceDesc, srv)
}

func _HEService_GenerateKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyGenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HEServiceServer).GenerateKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/he_service.HEService/GenerateKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HEServiceServer).GenerateKeys(ctx, req.(*KeyGenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HEService_Encrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HEServiceServer).Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/he_service.HEService/Encrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HEServiceServer).Encrypt(ctx, req.(*EncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HEService_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HEServiceServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/he_service.HEService/Decrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HEServiceServer).Decrypt(ctx, req.(*DecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HEService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HEServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/he_service.HEService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HEServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HEService_Multiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HEServiceServer).Multiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/he_service.HEService/Multiply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HEServiceServer).Multiply(ctx, req.(*MultiplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HEService_ServiceDesc is the grpc.ServiceDesc for HEService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HEService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "he_service.HEService",
	HandlerType: (*HEServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateKeys",
			Handler:    _HEService_GenerateKeys_Handler,
		},
		{
			MethodName: "Encrypt",
			Handler:    _HEService_Encrypt_Handler,
		},
		{
			MethodName: "Decrypt",
			Handler:    _HEService_Decrypt_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _HEService_Add_Handler,
		},
		{
			MethodName: "Multiply",
			Handler:    _HEService_Multiply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/he_service.proto",
}
